In [ ]:
# read data from file and handle null values
import pandas as pd
df = pd.read_csv(r'E:\DataSets\archive (2)\orders.csv',na_values = ['Not Available','unknown'])
df['Ship Mode'].unique()

In [ ]:
#rename columns names...make them lower case and repalce space with under scores
#df.columns
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df.head(3)

In [12]:
#creating new columns called [discount],[sale_price],['profit'] with existing columns list_price and discount_percent
df['discount']=(df['list_price']*df['discount_percent']*.01).round(2)
df['sale_price']=(df['list_price']-df['discount']).round(2)
df['profit']=(df['sale_price']-df['cost_price']).round(2)
df.head(3)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5

In [13]:
#convert order_date from object datatype to (datetime)
df['order_date']=pd.to_datetime(df['order_date'],format="%Y-%m-%d")

In [14]:
#drop cost price,list price and discount_percent
df.drop(columns=['cost_price','list_price','discount_percent'],inplace=True,errors='ignore')

In [7]:
df.tail(3)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sale_price,profit
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,4,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,2,7.2,232.8,22.8

In [15]:
#load the data into sql server using replace option
import sqlalchemy as sal

# Replace 'your_password' and 'your_database_name' with your actual MySQL details
engine = sal.create_engine(
    'mysql+pymysql://root:12345@localhost:3306/orders_DB'
)
conn = engine.connect()

In [16]:
df.to_sql(
    name='df_orders',
    con=conn,
    index=False,
    if_exists='replace',
)

conn.close()